[package]
name = "rust-marks"
version = "0.5.0"
authors = ["Sigurd Holsen <sighol@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
